name: Build Windows EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5

      - run: uv run pyinstaller --name dcs_mse --icon icon.ico --onefile dcs_mse.py --clean

      - uses: actions/upload-artifact@v4
        with:
          name: dcs_mse
          path: dist/dcs_mse.exe
